server:
  port: 8002
spring:
  application:
    name: consumer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      wuhu: http://localhost:8000/eureka/
      hefei: http://localhost:8000/eureka/
      defaultZone: http://localhost:8000/eureka/
    #      配置该微服务的所属区,一个服务允许的区只能有一个
    region: anhui
    #      配置指定的zone zone相当于机房 一个region下有多个zone
    availability-zones:
      jiangsu: nanjing,zhenjiang
      anhui: wuhu,hefei
#      默认为true,这里还是写一下,这个配置是说这个微服务是否倾向于使用同一zone下的注册中心
    prefer-same-zone-eureka: true
  instance:
    hostname: consumer1
#    默认的instanceid可以在面板上看到,就是ip+应用名+端口号 这里修改后就会直接变成consumer1
    instance-id: consumer1
#    每隔30s向注册中心发送心跳
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
#    指定zone不用这个,我觉得这个参数p用没有
    metadata-map:
      zone: wuhu

