spring:
  application:
    name: product
  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: w4247794
    url: jdbc:mysql://120.27.231.86/cloud_order?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
server:
  port: 8700
eureka:
  instance:
#    instance-id: product1
#  client:
#    service-url:
#      defaultZone: http://localhost:8000/eureka/
#    fetch-registry: true
#    register-with-eureka: true

feign:
  hystrix:
    enabled: true
    